[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/auth/*"
  to = "https://shortify-5rrs.onrender.com/api/auth/:splat"
  status = 200

[[redirects]]
  from = "/api/user/*"
  to = "https://shortify-5rrs.onrender.com/api/user/:splat"
  status = 200

[[redirects]]
  from = "/api/url/*"
  to = "https://shortify-5rrs.onrender.com/api/url/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
