[build]
  # Directory to deploy
  publish = "dist"
  # Command to build the project
  command = "npm run build"

[[redirects]]
  # Redirect all API requests to the backend server
  from = "/api/*"
  to = "https://shortify-5rrs.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  # Redirect all other requests to the index.html for SPA routing
  from = "/*"
  to = "/index.html"
  status = 200
